# Generated by Django 4.0 on 2021-12-11 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_first_name_alter_driver_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(message='First name must be Alphanumeric', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator(message='Last name must be Alphanumeric', regex='^[a-zA-Z]*$')]),
        ),
    ]
