# Generated by Django 4.0 on 2021-12-10 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(help_text='Please use the following format: <em>AA 1234 OO</em>.', max_length=10, validators=[django.core.validators.RegexValidator(message='Incorrect number. Please use the following format: AA 1234 OO', regex='\\b[A-Z]{2}\\s[0-9]{4}\\s[A-Z]{2}\\b')]),
        ),
    ]
