# Generated by Django 4.0 on 2021-12-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_first_name_alter_driver_last_name'),
        ('vehicle', '0003_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver'),
        ),
    ]
